
set(SWIFT_HOST_VARIANT_SDK ANDROID CACHE STRING "")
set(SWIFT_HOST_VARIANT_ARCH x86_64 CACHE STRING "")

# build just the standard library
set(SWIFT_INCLUDE_TOOLS NO CACHE BOOL "")
set(SWIFT_INCLUDE_TESTS NO CACHE BOOL "")
set(SWIFT_INCLUDE_DOCS NO CACHE BOOL "")

# build with the host compiler
set(SWIFT_BUILD_RUNTIME_WITH_HOST_COMPILER YES CACHE BOOL "")

# android configuration
set(SWIFT_ANDROID_API_LEVEL ${CMAKE_ANDROID_API} CACHE STRING "")
set(SWIFT_ANDROID_NDK_PATH ${CMAKE_ANDROID_NDK} CACHE STRING "")
set(SWIFT_ANDROID_NDK_GCC_VERSION 4.9 CACHE STRING "")

# TODO(compnerd) we should fix the lld.exe spelling
set(SWIFT_ENABLE_LLD_LINKER FALSE CACHE BOOL "")
set(SWIFT_ENABLE_GOLD_LINKER TRUE CACHE BOOL "")

