
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /GS- /Oy /Gw /Gy" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS "/INCREMENTAL:NO" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "/INCREMENTAL:NO" CACHE STRING "" FORCE)

# Set the CMAKE_SYSTEM_PROCESSOR for the LLVM build
set(CMAKE_SYSTEM_PROCESSOR ARM64 CACHE STRING "" FORCE)

