
# NOTE(compnerd) default the compiler to `cl` but permit overriding it
set(CMAKE_C_COMPILER cl CACHE STRING "")
set(CMAKE_CXX_COMPILER cl CACHE STRING "")
set(CMAKE_MT mt CACHE STRING "")

set(CMAKE_C_FLAGS "${CMAKE_CXX_FLAGS} /GS- /Oy /Gw /Gy" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /GS- /Oy /Gw /Gy" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS "/INCREMENTAL:NO" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "/INCREMENTAL:NO" CACHE STRING "" FORCE)

