
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /GS- /Oy" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS "/INCREMENTAL:NO" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "/INCREMENTAL:NO" CACHE STRING "" FORCE)

