runners:
  - name: win11-23h2-pro-arm64-16
    cloud: azure
    instance_type: Standard_D16plds_v5
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-23h2-pro-arm64/versions/2024.07.09"
    labels:
      - cirun-win11-23h2-pro-arm64-16-2024-07-09
    extra_config:
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive
  - name: win11-23h2-pro-arm64-64
    cloud: azure
    instance_type: Standard_D64plds_v5
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-23h2-pro-arm64/versions/2024.07.09"
    labels:
      - cirun-win11-23h2-pro-arm64-64-2024-07-09
    extra_config:
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive
  - name: win11-23h2-pro-x64-16
    cloud: azure
    instance_type: Standard_F16s_v2
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-23h2-pro-x64/versions/2024.07.09"
    labels:
      - cirun-win11-23h2-pro-x64-16-2024-07-09
    extra_config:
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive
  - name: win11-23h2-pro-x64-64
    cloud: azure
    instance_type: Standard_D64ads_v5
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-23h2-pro-x64/versions/2024.07.09"
    labels:
      - cirun-win11-23h2-pro-x64-64-2024-07-09
    extra_config:
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive
