# Self-Hosted Github Action Runners on Azure via https://cirun.io
#
# cirun reference:
# - https://docs.cirun.io/reference/yaml
# - https://docs.cirun.io/cloud/azure
# - https://docs.cirun.io/custom-images/cloud-custom-images#azure-custom-images
#
# Updating the base image version:
# - ./scripts/python/roll_cirun.py --version <new_version>
#
# VM shapes:
# - ARM64 (Ampere): https://learn.microsoft.com/en-us/azure/virtual-machines/dplsv5-dpldsv5-series
#   ARM64 (Cobalt): https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/general-purpose/dpldsv6-series
# - X64: https://learn.microsoft.com/en-us/azure/virtual-machines/fsv2-series
# - X64: https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/general-purpose/dadsv5-series
runners:

# Build definitions used in main branch
  - name: win11-pro-arm64-16
    cloud: azure
    instance_type: Standard_D16plds_v5
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-24h2-pro-arm64/versions/2025.10.15"
    labels:
      - cirun-win11-pro-arm64-16
    extra_config:
      enable_public_ip: true
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive
  - name: win11-pro-arm64-64
    cloud: azure
    instance_type: Standard_D64plds_v5
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-24h2-pro-arm64/versions/2025.10.15"
    labels:
      - cirun-win11-pro-arm64-64
    extra_config:
      enable_public_ip: true
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive
  - name: win11-pro-x64-16
    cloud: azure
    instance_type: Standard_F16s_v2
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-24h2-pro-x64/versions/2025.10.15"
    labels:
      - cirun-win11-pro-x64-16
    extra_config:
      enable_public_ip: true
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive
  - name: win11-pro-x64-64
    cloud: azure
    instance_type: Standard_D64ads_v5
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-24h2-pro-x64/versions/2025.10.15"
    labels:
      - cirun-win11-pro-x64-64
    extra_config:
      enable_public_ip: true
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive

  # Build definitions used by release/6.3
  - name: win11-pro-arm64-16
    cloud: azure
    instance_type: Standard_D16plds_v5
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-24h2-pro-arm64/versions/2025.10.15"
    labels:
      - cirun-win11-pro-arm64-16-2025-11-21
    extra_config:
      enable_public_ip: true
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive
  - name: win11-pro-arm64-64
    cloud: azure
    instance_type: Standard_D64plds_v5
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-24h2-pro-arm64/versions/2025.10.15"
    labels:
      - cirun-win11-pro-arm64-64-2025-11-21
    extra_config:
      enable_public_ip: true
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive
  - name: win11-pro-x64-16
    cloud: azure
    instance_type: Standard_F16s_v2
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-24h2-pro-x64/versions/2025.10.15"
    labels:
      - cirun-win11-pro-x64-16-2025-11-21
    extra_config:
      enable_public_ip: true
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive
  - name: win11-pro-x64-64
    cloud: azure
    instance_type: Standard_D64ads_v5
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-24h2-pro-x64/versions/2025.10.15"
    labels:
      - cirun-win11-pro-x64-64-2025-11-21
    extra_config:
      enable_public_ip: true
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive

  # Build definitions used by release/6.1
  - name: win11-23h2-pro-arm64-16
    cloud: azure
    instance_type: Standard_D16plds_v5
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-23h2-pro-arm64/versions/2025.03.13"
    labels:
      - cirun-win11-23h2-pro-arm64-16-2025-03-13
    extra_config:
      enable_public_ip: true
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive
  - name: win11-23h2-pro-arm64-64
    cloud: azure
    instance_type: Standard_D64plds_v5
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-23h2-pro-arm64/versions/2025.03.13"
    labels:
      - cirun-win11-23h2-pro-arm64-64-2025-03-13
    extra_config:
      enable_public_ip: true
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive
  - name: win11-23h2-pro-x64-16
    cloud: azure
    instance_type: Standard_F16s_v2
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-23h2-pro-x64/versions/2025.03.13"
    labels:
      - cirun-win11-23h2-pro-x64-16-2025-03-13
    extra_config:
      enable_public_ip: true
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive
  - name: win11-23h2-pro-x64-64
    cloud: azure
    instance_type: Standard_D64ads_v5
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-23h2-pro-x64/versions/2025.03.13"
    labels:
      - cirun-win11-23h2-pro-x64-64-2025-03-13
    extra_config:
      enable_public_ip: true
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive

  # Build definitions used by release/6.2
  - name: win11-23h2-pro-arm64-16
    cloud: azure
    instance_type: Standard_D16plds_v5
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-23h2-pro-arm64/versions/2024.12.19"
    labels:
      - cirun-win11-23h2-pro-arm64-16-2024-12-19
    extra_config:
      enable_public_ip: true
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive
  - name: win11-23h2-pro-arm64-64
    cloud: azure
    instance_type: Standard_D64plds_v5
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-23h2-pro-arm64/versions/2024.12.19"
    labels:
      - cirun-win11-23h2-pro-arm64-64-2024-12-19
    extra_config:
      enable_public_ip: true
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive
  - name: win11-23h2-pro-x64-16
    cloud: azure
    instance_type: Standard_F16s_v2
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-23h2-pro-x64/versions/2024.12.19"
    labels:
      - cirun-win11-23h2-pro-x64-16-2024-12-19
    extra_config:
      enable_public_ip: true
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive
  - name: win11-23h2-pro-x64-64
    cloud: azure
    instance_type: Standard_D64ads_v5
    machine_image: "/subscriptions/88c2ce23-b441-4d79-8f1c-50d9bc95ed08/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-23h2-pro-x64/versions/2024.12.19"
    labels:
      - cirun-win11-23h2-pro-x64-64-2024-12-19
    extra_config:
      enable_public_ip: true
      runner_path: "D:\\r"
      runner_user: runner
      run_as: interactive
