pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/macOS.yml
      - .ci/templates/toolchain.yml
resources:
  pipelines:
    - pipeline: icu
      source: 'ICU'
    - pipeline: tensorflow
      source: 'tensorflow'

  repositories:
    - repository: apple/llvm-project
      type: github
      name: apple/llvm-project
      ref: swift/main
      endpoint: GitHub

    - repository: apple/swift
      type: github
      name: apple/swift
      ref: main
      endpoint: GitHub

    - repository: apple/swift-cmark
      type: github
      name: apple/swift-cmark
      ref: main
      endpoint: GitHub

    - repository: apple/swift-corelibs-libdispatch
      type: github
      name: apple/swift-corelibs-libdispatch
      ref: main
      endpoint: GitHub

    - repository: apple/swift-corelibs-foundation
      type: github
      name: apple/swift-corelibs-foundation
      ref: main
      endpoint: GitHub

    - repository: apple/swift-corelibs-xctest
      type: github
      name: apple/swift-corelibs-xctest
      ref: main
      endpoint: GitHub

    - repository: apple/swift-llbuild
      type: github
      name: apple/swift-llbuild
      ref: main
      endpoint: GitHub

    - repository: apple/swift-tools-support-core
      type: github
      name: apple/swift-tools-support-core
      ref: main
      endpoint: GitHub

    - repository: apple/swift-package-manager
      type: github
      name: apple/swift-package-manager
      ref: main
      endpoint: GitHub

    - repository: apple/indexstore-db
      type: github
      name: apple/indexstore-db
      ref: main
      endpoint: GitHub

    - repository: apple/sourcekit-lsp
      type: github
      name: apple/sourcekit-lsp
      ref: main
      endpoint: GitHub

    - repository: tensorflow/swift-apis
      type: github
      name: tensorflow/swift-apis
      ref: main
      endpoint: GitHub

    - repository: pvieito/PythonKit
      type: github
      name: pvieito/PythonKit
      ref: master
      endpoint: GitHub

    - repository: jpsim/Yams
      type: github
      name: jpsim/Yams
      ref: master
      endpoint: GitHub

    - repository: apple/swift-driver
      type: github
      name: apple/swift-driver
      ref: main
      endpoint: GitHub

    - repository: apple/swift-argument-parser
      type: github
      name: apple/swift-argument-parser
      ref: main
      endpoint: GitHub

schedules:
  - cron: "0 0 * * *"
    branches:
      include:
        - master
    always: true
    displayName: "Nightly Build"
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/macOS.yml
      - .ci/templates/toolchain.yml
stages:
  - stage: toolchain
    pool:
      vmImage: 'macOS-10.14'
    jobs:
      - template: templates/toolchain.yml
        parameters:
          arch: x86_64
          host: x64
          platform: darwin

          triple: x86_64-apple-macosx10.14

          ICU_VERSION: 0
          LLVM_OPTIONS: -DLLVM_INCLUDE_TESTS=NO
          LLDB_OPTIONS: -DLLDB_USE_SYSTEM_DEBUGSERVER=ON -DLLDB_INCLUDE_TESTS=NO -DLLDB_BUILD_FRAMEWORK=YES
          SWIFT_OPTIONS: -DSWIFT_INCLUDE_TESTS=NO -DSWIFT_BUILD_STDLIB_EXTRA_TOOLCHAIN_CONTENT=NO

          RUN_TESTS: false
          RUN_VALIDATION_TESTS: false

  - stage: sdk
    pool:
      vmImage: macOS-10.15
    jobs:
      - template: templates/macos-sdk.yml
        parameters:
          arch: x86_64
          host: x64
          platform: darwin

          triple: x86_64-apple-macosx10.14

          ICU_VERSION: 0
          SWIFT_OPTIONS: -D CMAKE_CXX_FLAGS="-isystem /Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1"

          os: MacOSX
          proc: amd64

  - stage: package
    pool:
      vmImage: 'macOS-10.15'
    jobs:
      - template: templates/xctoolchain.yml
        parameters:
          arch: x86_64
          host: x64
          platform: darwin

          alias: swift
