pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/sqlite3.yml
      - .ci/templates/sqlite3.yml
schedules:
  - cron: "0 8 * * *"
    branches:
      include:
        - master
    always: true
    displayName: "Nightly (8:00 AM) Build"
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/sqlite3.yml
      - .ci/templates/sqlite3.yml
stages:
  - stage: android
    dependsOn:
    pool:
      vmImage: 'windows-2019'
    jobs:
      - template: templates/sqlite3.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: armv7
          host: arm
          platform: android

      - template: templates/sqlite3.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: aarch64
          host: arm64
          platform: android

      - template: templates/sqlite3.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: x86_64
          host: x64
          platform: android

      - template: templates/sqlite3.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: i686
          host: x86
          platform: android

  - stage: linux
    dependsOn:
    pool:
      vmImage: 'ubuntu-18.04'
    jobs:
      - template: templates/sqlite3.yml
        parameters:
          arch: x86_64
          host: x64
          platform: linux

  - stage: windows
    dependsOn:
    pool:
      vmImage: 'windows-2019'
    jobs:
      - template: templates/sqlite3.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: armv7
          host: arm
          platform: windows

      - template: templates/sqlite3.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: aarch64
          host: arm64
          platform: windows

      - template: templates/sqlite3.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: x86_64
          host: x64
          platform: windows

      - template: templates/sqlite3.yml
        parameters:
          VisualStudio: 2019/Enterprise

          arch: i686
          host: x86
          platform: windows
