pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/toolchain-linux-x64.yml
      - .ci/templates/toolchain.yml
      - cmake/caches/org.compnerd.dt.cmake
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/toolchain-linux-x64.yml
      - .ci/templates/toolchain.yml
      - cmake/caches/org.compnerd.dt.cmake

resources:
  pipelines:
    - pipeline: icu
      source: 'ICU'

    - pipeline: xml2
      source: 'XML2'

    - pipeline: curl
      source: 'CURL'

    - pipeline: zlib
      source: 'zlib'

    - pipeline: sqlite
      source: 'SQLite'

  repositories:
    - repository: apple/llvm-project
      type: github
      name: apple/llvm-project
      ref: swift/main
      endpoint: GitHub

    - repository: apple/swift
      type: github
      name: apple/swift
      ref: main
      endpoint: GitHub

    - repository: apple/swift-cmark
      type: github
      name: apple/swift-cmark
      ref: main
      endpoint: GitHub

    - repository: apple/swift-corelibs-libdispatch
      type: github
      name: apple/swift-corelibs-libdispatch
      ref: main
      endpoint: GitHub

    - repository: apple/swift-corelibs-foundation
      type: github
      name: apple/swift-corelibs-foundation
      ref: main
      endpoint: GitHub

    - repository: apple/swift-corelibs-xctest
      type: github
      name: apple/swift-corelibs-xctest
      ref: main
      endpoint: GitHub

    - repository: apple/swift-llbuild
      type: github
      name: apple/swift-llbuild
      ref: main
      endpoint: GitHub

    - repository: apple/swift-tools-support-core
      type: github
      name: apple/swift-tools-support-core
      ref: main
      endpoint: GitHub

    - repository: apple/swift-package-manager
      type: github
      name: apple/swift-package-manager
      ref: main
      endpoint: GitHub

    - repository: apple/indexstore-db
      type: github
      name: apple/indexstore-db
      ref: main
      endpoint: GitHub

    - repository: apple/sourcekit-lsp
      type: github
      name: apple/sourcekit-lsp
      ref: main
      endpoint: GitHub

    - repository: tensorflow/swift-apis
      type: github
      name: tensorflow/swift-apis
      ref: main
      endpoint: GitHub

    - repository: pvieito/PythonKit
      type: github
      name: pvieito/PythonKit
      ref: master
      endpoint: GitHub

    - repository: jpsim/Yams
      type: github
      name: jpsim/Yams
      ref: master
      endpoint: GitHub

    - repository: apple/swift-driver
      type: github
      name: apple/swift-driver
      ref: main
      endpoint: GitHub

    - repository: apple/swift-argument-parser
      type: github
      name: apple/swift-argument-parser
      ref: main
      endpoint: GitHub

schedules:
  - cron: "0 * * * *"
    branches:
      include:
        - master
    always: true
    displayName: "Hourly Build"

stages:
  - stage: toolchain
    pool: FlowKey
    jobs:
      - template: templates/toolchain.yml
        parameters:
          arch: x86_64
          host: x64
          platform: linux

          triple: x86_64-unknown-linux-gnu

          ICU_VERSION: 67
          SWIFT_OPTIONS: -DICU_UC_INCLUDE_DIRS=$(icu.directory)/usr/include/unicode -DICU_UC_LIBRARIES=$(icu.directory)/usr/lib/libicuuc$(icu.version).so -DICU_I18N_INCLUDE_DIRS=$(icu.directory)/usr/include -DICU_I18N_LIBRARIES=$(icu.directory)/usr/lib/libicuin$(icu.version).so -DSWIFT_LINUX_x86_64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_LINUX_x86_64_ICU_UC=$(icu.directory)/usr/lib/libicuuc$(icu.version).so -DSWIFT_LINUX_x86_64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_LINUX_x86_64_ICU_I18N=$(icu.directory)/usr/lib/libicuin$(icu.version).so -DSWIFT_BUILD_DYNAMIC_STDLIB=YES -DSWIFT_BUILD_DYNAMIC_SDK_OVERLAY=YES

          RUN_TESTS: false
          RUN_VALIDATION_TESTS: false

  - stage: sdk
    pool: FlowKey
    jobs:
      - template: templates/linux-sdk.yml
        parameters:
          arch: x86_64
          host: x64
          platform: linux

          triple: x86_64-unknown-linux-gnu

          os: Linux
          proc: amd64

          ICU_VERSION: 67
          SWIFT_OPTIONS: -D ICU_UC_INCLUDE_DIRS=$(icu.directory)/usr/include/unicode -D ICU_UC_LIBRARIES=$(icu.directory)/usr/lib/libicuuc$(icu.version).so -D ICU_I18N_INCLUDE_DIRS=$(icu.directory)/usr/include -D ICU_I18N_LIBRARIES=$(icu.directory)/usr/lib/libicuin$(icu.version).so -D SWIFT_LINUX_x86_64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -D SWIFT_LINUX_x86_64_ICU_UC=$(icu.directory)/usr/lib/libicuuc$(icu.version).so -D SWIFT_LINUX_x86_64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -D SWIFT_LINUX_x86_64_ICU_I18N=$(icu.directory)/usr/lib/libicuin$(icu.version).so

  - stage: devtools
    pool: FlowKey
    jobs:
      - template: templates/linux-devtools.yml
        parameters:
          arch: x86_64
          host: x64
          platform: linux

          os: Linux
          proc: amd64

  - stage: package
    pool: FlowKey
    jobs:
      - template: templates/toolchain-deb.yml
        parameters:
          arch: x86_64
          host: x64
          platform: linux

          os: Linux
          proc: amd64

      - template: templates/icu-deb.yml
        parameters:
          arch: x86_64
          host: x64
          platform: linux

          os: Linux
          proc: amd64

          ICU_VERSION: 67

      - template: templates/sdk-deb.yml
        parameters:
          arch: x86_64
          host: x64
          platform: linux

          os: Linux
          proc: amd64

      - template: templates/devtools-deb.yml
        parameters:
          arch: x86_64
          host: x64
          platform: linux

          os: Linux
          proc: amd64
