pr:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/vs2019-google.yml
      - .ci/templates/toolchain.yml
      - .ci/templates/toolchain-msi.yml
      - .ci/templates/windows-sdk.yml
      - .ci/templates/windows-devtools.yml
resources:
  pipelines:
    - pipeline: icu
      source: 'ICU'
    - pipeline: xml2
      source: 'XML2'
    - pipeline: curl
      source: 'CURL'
    - pipeline: zlib
      source: 'zlib'
    - pipeline: sqlite
      source: 'SQLite'

  repositories:
    - repository: apple/llvm-project
      type: github
      name: apple/llvm-project
      ref: swift/main
      endpoint: GitHub

    - repository: apple/swift
      type: github
      name: apple/swift
      ref: main
      endpoint: GitHub

    - repository: apple/swift-cmark
      type: github
      name: apple/swift-cmark
      ref: main
      endpoint: GitHub

    - repository: apple/swift-corelibs-libdispatch
      type: github
      name: apple/swift-corelibs-libdispatch
      ref: main
      endpoint: GitHub

    - repository: apple/swift-corelibs-foundation
      type: github
      name: apple/swift-corelibs-foundation
      ref: main
      endpoint: GitHub

    - repository: apple/swift-corelibs-xctest
      type: github
      name: apple/swift-corelibs-xctest
      ref: main
      endpoint: GitHub

    - repository: apple/swift-llbuild
      type: github
      name: apple/swift-llbuild
      ref: main
      endpoint: GitHub

    - repository: apple/swift-tools-support-core
      type: github
      name: apple/swift-tools-support-core
      ref: main
      endpoint: GitHub

    - repository: apple/swift-package-manager
      type: github
      name: apple/swift-package-manager
      ref: main
      endpoint: GitHub

    - repository: apple/indexstore-db
      type: github
      name: apple/indexstore-db
      ref: main
      endpoint: GitHub

    - repository: apple/sourcekit-lsp
      type: github
      name: apple/sourcekit-lsp
      ref: main
      endpoint: GitHub

    - repository: jpsim/Yams
      type: github
      name: jpsim/Yams
      ref: main
      endpoint: GitHub

    - repository: apple/swift-driver
      type: github
      name: apple/swift-driver
      ref: main
      endpoint: GitHub

    - repository: apple/swift-argument-parser
      type: github
      name: apple/swift-argument-parser
      ref: main
      endpoint: GitHub

    - repository: apple/swift-crypto
      type: github
      name: apple/swift-crypto
      ref: main
      endpoint: GitHub

    - repository: apple/swift-collections
      type: github
      name: apple/swift-collections
      ref: main
      endpoint: GitHub

    - repository: apple/swift-system
      type: github
      name: apple/swift-system
      ref: main
      endpoint: GitHub

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - .ci/vs2019-google.yml
      - .ci/templates/toolchain.yml
      - .ci/templates/toolchain-msi.yml
      - .ci/templates/windows-sdk.yml
      - .ci/templates/windows-devtools.yml
stages:
  - stage: toolchain
    pool: Google
    jobs:
      - template: templates/toolchain.yml
        parameters:
          VisualStudio: 2019/Community

          arch: x86_64
          host: x64
          platform: windows

          triple: x86_64-unknown-windows-msvc

          ICU_VERSION: 67

          LLVM_OPTIONS: -DLLVM_ENABLE_LIBEDIT=NO -DLLVM_PARALLEL_LINK_JOBS=2 -DPYTHON_EXECUTABLE=C:/Python27amd64/python.exe -DLLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=YES
          SWIFT_OPTIONS: -DSWIFT_WINDOWS_x86_64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_x86_64_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_x86_64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_x86_64_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DSWIFT_PARALLEL_LINK_JOBS=2 -DSWIFT_BUILD_DYNAMIC_STDLIB=YES -DSWIFT_BUILD_DYNAMIC_SDK_OVERLAY=YES

          RUN_TESTS: true
          RUN_VALIDATION_TESTS: false

      - template: templates/toolchain.yml
        parameters:
          VisualStudio: 2019/Community

          arch: aarch64
          host: arm64
          platform: windows

          triple: aarch64-unknown-windows-msvc

          ICU_VERSION: 67

          # NOTE(compnerd) DIA does not contain ARM64 diaguids.lib
          LLVM_OPTIONS: -DLLVM_ENABLE_LIBEDIT=NO -DLLVM_ENABLE_DIA_SDK=NO -DLLVM_INCLUDE_TESTS=NO -DCLANG_INCLUDE_TESTS=NO -DLLD_INCLUDE_TESTS=NO -DPYTHON_EXECUTABLE=C:/Python27amd64/python.exe -DLLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=YES
          # NOTE(compnerd) disable python support as we need an ARM64 build of
          # python to support this.
          LLDB_OPTIONS: -DLLDB_ENABLE_PYTHON=NO
          # NOTE(compnerd) cannot build SyntaxParserLib and SourceKit due to
          # libdispatch's dependency on clang
          SWIFT_OPTIONS: -DSWIFT_INCLUDE_TESTS=NO -DSWIFT_ENABLE_SOURCEKIT_TESTS=NO -DSWIFT_BUILD_SYNTAXPARSERLIB=NO -DSWIFT_BUILD_SOURCEKIT=NO -DSWIFT_WINDOWS_aarch64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_aarch64_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_aarch64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_aarch64_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib

          RUN_TESTS: false
          RUN_VALIDATION_TESTS: false

  - stage: windows_sdk
    dependsOn: toolchain
    displayName: 'Windows SDK'
    pool: Google
    jobs:
      - template: templates/windows-sdk.yml
        parameters:
          VisualStudio: 2019/Community

          arch: armv7
          host: arm
          platform: windows

          triple: armv7-unknown-windows-msvc

          os: Windows
          proc: arm

          ICU_VERSION: 67

          SWIFT_OPTIONS: -DSWIFT_WINDOWS_armv7_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_armv7_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_armv7_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_armv7_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DPYTHON_EXECUTABLE=C:/Python27amd64/python.exe

      - template: templates/windows-sdk.yml
        parameters:
          VisualStudio: 2019/Community

          arch: aarch64
          host: arm64
          platform: windows

          triple: aarch64-unknown-windows-msvc

          os: Windows
          proc: arm64

          ICU_VERSION: 67

          SWIFT_OPTIONS: -DSWIFT_WINDOWS_aarch64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_aarch64_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_aarch64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_aarch64_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DPYTHON_EXECUTABLE=C:/Python27amd64/python.exe

      - template: templates/windows-sdk.yml
        parameters:
          VisualStudio: 2019/Community

          arch: x86_64
          host: x64
          platform: windows

          triple: x86_64-unknown-windows-msvc

          os: Windows
          proc: amd64

          ICU_VERSION: 67

          SWIFT_OPTIONS: -DSWIFT_WINDOWS_x86_64_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_x86_64_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_x86_64_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_x86_64_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DPYTHON_EXECUTABLE=C:/Python27amd64/python.exe

      - template: templates/windows-sdk.yml
        parameters:
          VisualStudio: 2019/Community

          arch: i686
          host: x86
          platform: windows

          triple: i686-unknown-windows-msvc

          os: Windows
          proc: i686

          ICU_VERSION: 67

          SWIFT_OPTIONS: -DSWIFT_WINDOWS_i686_ICU_UC_INCLUDE=$(icu.directory)/usr/include/unicode -DSWIFT_WINDOWS_i686_ICU_UC=$(icu.directory)/usr/lib/icuuc$(icu.version).lib -DSWIFT_WINDOWS_i686_ICU_I18N_INCLUDE=$(icu.directory)/usr/include -DSWIFT_WINDOWS_i686_ICU_I18N=$(icu.directory)/usr/lib/icuin$(icu.version).lib -DPYTHON_EXECUTABLE=C:/Python27amd64/python.exe

  - stage: devtools
    dependsOn: windows_sdk
    pool: Google
    jobs:
      - template: templates/windows-devtools.yml
        parameters:
          VisualStudio: 2019/Community

          arch: aarch64
          host: arm64
          platform: windows

          os: Windows
          proc: arm64

          ICU_VERSION: 67
          SQLITE_VERSION: 3.34.0

      - template: templates/windows-devtools.yml
        parameters:
          VisualStudio: 2019/Community

          arch: x86_64
          host: x64
          platform: windows

          os: Windows
          proc: amd64

          ICU_VERSION: 67
          SQLITE_VERSION: 3.34.0

  - stage: package_windows_toolchain
    dependsOn: toolchain
    displayName: package Toolchain
    pool: Google
    jobs:
      - template: templates/toolchain-msi.yml
        parameters:
          VisualStudio: 2019/Community

          arch: x86_64
          host: x64
          platform: windows

          os: Windows
          proc: amd64

  - stage: package_windows_sdk
    dependsOn: windows_sdk
    displayName: package SDK
    pool: Google
    jobs:
      - template: templates/sdk-msi.yml
        parameters:
          VisualStudio: 2019/Community

          arch: x86_64
          host: x64
          platform: windows

          os: Windows
          proc: amd64

  - stage: package_windows_devtools
    dependsOn: devtools
    displayName: package devtools
    pool: Google
    jobs:
      - template: templates/devtools-msi.yml
        parameters:
          VisualStudio: 2019/Community

          arch: x86_64
          host: x64
          platform: windows

          os: Windows
          proc: amd64

  - stage: package_icu
    dependsOn: []
    displayName: package ICU
    pool: Google
    jobs:
      - template: templates/icu-msi.yml
        parameters:
          VisualStudio: 2019/Community

          arch: x86_64
          host: x64
          platform: windows

          os: Windows
          proc: amd64

  - stage: package_bundle
    dependsOn:
      - package_windows_toolchain
      - package_windows_devtools
      - package_windows_sdk
      - package_icu
    displayName: package
    pool: Google
    jobs:
      - template: templates/swift-installer-bundle.yml
        parameters:
          VisualStudio: 2019/Community

          arch: x86_64
          host: x64
          platform: windows

          os: Winodws
          proc: amd64
