name: 'Windows SDK'
jobs:
  - template: templates/windows-sdk.yml
    parameters:
      arch: 'x86_64'
      build: 'x64'
      triple: 'x86_64-unknown-windows-msvc'

  - template: templates/windows-sdk.yml
    parameters:
      arch: 'aarch64'
      build: 'arm64'
      triple: 'aarch64-unknown-windows-msvc'