name: "Setup sccache"
description: "Sets up sccache with S3 or local disk configuration"

inputs:
  disk-max-size:
    description: "The maximum size of the local disk cache in MB if S3 is unavailable."
    required: true
  disk-cache-key:
    description: "The key to use for the local disk cache."
    required: true
  s3-bucket:
    description: "The s3 bucket to use for cache storage."
    required: false
  s3-bucket-encryption:
    description: "Whether to enable server-side encryption for the S3 bucket."
    required: false
    default: "true"
  aws-arn:
    description: "The ARN of the AWS role to assume which has read/write access to the S3 bucket."
    required: false
  aws-region:
    description: "The region of the S3 bucket to use for the cache"
    required: false

runs:
  using: composite
  steps:
    - name: Configure caching enviornment
      shell: pwsh
      env:
        INPUT_AWS_ARN: ${{ inputs.aws-arn }}
        INPUT_S3_BUCKET: ${{ inputs.s3-bucket }}
        INPUT_S3_BUCKET_ENCRYPTION: ${{ inputs.s3-bucket-encryption }}
        INPUT_AWS_REGION: ${{ inputs.aws-region }}
      run: |
        $AWSArn = $env:INPUT_AWS_ARN
        if ($AWSArn) {
          $requiredParams = @{
              's3-bucket' = $env:INPUT_S3_BUCKET
              's3-bucket-encryption' = $env:INPUT_S3_BUCKET_ENCRYPTION
              'aws-region' = $env:INPUT_AWS_REGION
          }

          foreach ($param in $requiredParams.GetEnumerator()) {
              if ([string]::IsNullOrEmpty($param.Value)) {
                  Write-Error -Message "$($param.Key) input cannot be empty when aws-arn is provided" -ErrorAction Stop
              }
          }

          Write-Host "Using S3 bucket $env:INPUT_S3_BUCKET for cache storage."
          "SCCACHE_BUCKET=$env:INPUT_S3_BUCKET" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "SCCACHE_REGION=$env:INPUT_AWS_REGION" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "SCCACHE_S3_SERVER_SIDE_ENCRYPTION=$env:INPUT_S3_BUCKET_ENCRYPTION" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        } else {
          Write-Host "Using local disk cache."
          "SCCACHE_DIRECT=on" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        }

    - name: Authenticate to AWS
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
      if: inputs.aws-arn != ''
      with:
        role-to-assume: ${{ inputs.aws-arn }}
        role-session-name: ToolchainCISccacheAccess
        aws-region: ${{ inputs.aws-region }}
        special-characters-workaround: 'true' # special characters in secrets can cause SignatureDoesNotMatch errors

    - name: Setup sccache (remote)
      if: inputs.aws-arn != '' && steps.aws-credentials.outcome == 'success'
      uses: hendrikmuhs/ccache-action@63069e3931dedbf3b63792097479563182fe70d1 # v1.2.18
      with:
        variant: sccache

    - name: Setup sccache (local)
      if: inputs.aws-arn == ''
      uses: hendrikmuhs/ccache-action@63069e3931dedbf3b63792097479563182fe70d1 # v1.2.18
      with:
        max-size: ${{ inputs.disk-max-size }}
        key: ${{ inputs.disk-cache-key }}
        variant: sccache
