name: Pull Request - Development Snapshot

on:
  pull_request:
    branches:
      - 'main'
    files:
      - '.github/workflows/swift-toolchain.yml'

  workflow_dispatch:

jobs:
  context:
    name: Generate build context
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.context.outputs.matrix }}
    steps:
      - id: context
        run: |
          matrix=$(cat <<EOF
          {
            "include": [
              {
                "name": "github.windows.x64",
                "default_runner": "swift-build-windows-latest-8-cores",
                "compilers_runner": "swift-build-windows-latest-64-cores"
              },
              {
                "name": "cirun.windows.arm64",
                "default_runner": "cirun-win11-23h2-pro-arm64-16-2024-05-17",
                "compilers_runner": "cirun-win11-23h2-pro-arm64-64-2024-05-17"
              }
            ]
          }
          EOF
          )

          if [[ ${{ vars.USE_CIRUN }} != true ]]; then
            matrix=$(echo $matrix | jq 'del(.include[] | select(.name | contains("cirun")))')
          fi

          matrix=$(echo "$matrix" | jq -c)
          echo $matrix
          echo "matrix=$matrix" >> ${GITHUB_OUTPUT}

  call_development_snapshot:
    name: Development Snapshot (${{ matrix.name }})
    needs: [ context ]
    uses: ./.github/workflows/swift-toolchain.yml
    strategy:
      matrix: ${{ fromJson(needs.context.outputs.matrix) }}
    with:
      dry_run: true
      default_runner: ${{ matrix.default_runner }}
      compilers_runner: ${{ matrix.compilers_runner }}
    secrets: inherit
    permissions:
      contents: read
      pull-requests: read

