name: Swift SDK build

on:
  workflow_call:
    inputs:
      build_os:
        required: true
        type: string

      build_arch:
        required: true
        type: string

      sdk_type:
        required: true
        type: string

      os:
        required: true
        type: string

      arch:
        required: true
        type: string

      cpu:
        required: true
        type: string

      triple:
        required: true
        type: string

      triple_no_api_level:
        required: true
        type: string

      cc:
        required: true
        type: string

      cflags:
        required: true
        type: string

      cxx:
        required: true
        type: string

      cxxflags:
        required: true
        type: string

      swiftflags:
        required: true
        type: string

      linker_flags:
        required: true
        type: string

      extra_flags:
        required: true
        type: string

      curl_version:
        required: true
        type: string

      libxml2_version:
        required: true
        type: string

      llvm_project_revision:
        required: true
        type: string

      swift_collections_revision:
        required: true
        type: string

      swift_corelibs_foundation_revision:
        required: true
        type: string

      swift_corelibs_libdispatch_revision:
        required: true
        type: string

      swift_corelibs_xctest_revision:
        required: true
        type: string

      swift_experimental_string_processing_revision:
        required: true
        type: string

      swift_foundation_revision:
        required: true
        type: string

      swift_foundation_icu_revision:
        required: true
        type: string

      swift_revision:
        required: true
        type: string

      swift_testing_revision:
        required: true
        type: string

      zlib_version:
        required: true
        type: string

      ANDROID_NDK_VERSION:
        required: true
        type: string

      runner:
        required: true
        type: string

      debug_info:
        required: true
        type: boolean

      swift_version:
        required: true
        type: string

      build_android:
        required: true
        type: boolean

    secrets:
      SYMBOL_SERVER_PAT:
        required: true
      CERTIFICATE:
        required: true
      PASSPHRASE:
        required: true

defaults:
  run:
    shell: pwsh

permissions:
  id-token: write
  attestations: write

jobs:
  sdk:
    # Skip the SDK sub-build for the macOS build and for Android targets if Android is disabled.
    # This cancels the sub-build without failing it.
    if: ${{ inputs.build_os == 'Windows' && (inputs.os != 'Android' || inputs.build_android) }}
    runs-on: ${{ inputs.runner }}
    name: ${{ inputs.os }} ${{ inputs.arch }} ${{ inputs.sdk_type }} SDK

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          path: ${{ github.workspace }}/SourceCache/ci-build
          show-progress: false
      - uses: ./SourceCache/ci-build/.github/actions/setup-build
        with:
          setup-vs-dev-env: ${{ inputs.os == 'Windows' }}
          host-arch: ${{ inputs.arch }}

      - name: Compute workspace hash
        id: workspace_hash
        run: |
          $stringAsStream = [System.IO.MemoryStream]::new()
          $writer = [System.IO.StreamWriter]::new($stringAsStream)
          $writer.write("${{ github.workspace }}")
          $writer.Flush()
          $stringAsStream.Position = 0
          $hash = (Get-FileHash -Algorithm SHA256 -InputStream $stringAsStream).Hash
          echo "hash=$hash" >> $env:GITHUB_OUTPUT
      - name: Setup sccache
        uses: ./SourceCache/ci-build/.github/actions/setup-sccache
        with:
          s3-bucket: ${{ vars.SCCACHE_S3_BUCKET }}
          aws-region: ${{ vars.SCCACHE_AWS_REGION }}
          aws-arn: ${{ vars.SCCACHE_AWS_ARN }}
          disk-max-size: 500M
          disk-cache-key: ${{ steps.workspace_hash.outputs.hash }}-${{ inputs.os }}-${{ inputs.arch }}-${{ inputs.sdk_type }}-sdk

      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.os }}-${{ inputs.arch }}-libxml2-${{ inputs.libxml2_version }}
          path: ${{ github.workspace }}/BuildRoot/Library/libxml2-${{ inputs.libxml2_version }}/usr
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.os }}-${{ inputs.arch }}-curl-${{ inputs.curl_version }}
          path: ${{ github.workspace }}/BuildRoot/Library/curl-${{ inputs.curl_version }}/usr
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.os }}-${{ inputs.arch }}-zlib-${{ inputs.zlib_version }}
          path: ${{ github.workspace }}/BuildRoot/Library/zlib-${{ inputs.zlib_version }}/usr

      - name: Download Compilers
        uses: thebrowsercompany/gha-download-tar-artifact@59992d91335d4ecba543c8535f7d07238e42125d # main
        with:
          name: Windows-${{ inputs.build_arch }}-Asserts-compilers
          path: ${{ github.workspace }}/BinaryCache/Library
      - uses: thebrowsercompany/gha-download-tar-artifact@59992d91335d4ecba543c8535f7d07238e42125d # main
        with:
          name: ${{ inputs.os }}-${{ inputs.arch }}-stdlib
          path: ${{ github.workspace }}/BinaryCache/Library
      - uses: thebrowsercompany/gha-download-tar-artifact@59992d91335d4ecba543c8535f7d07238e42125d # main
        with:
          name: Windows-${{ inputs.build_arch }}-stdlib
          path: ${{ github.workspace }}/BinaryCache/Library
      - uses: actions/download-artifact@v4
        with:
          name: Windows-${{ inputs.build_arch }}-macros
          path: ${{ github.workspace }}/BinaryCache/Library
      - uses: actions/checkout@v4.2.2
        with:
          repository: apple/swift-corelibs-libdispatch
          ref: ${{ inputs.swift_corelibs_libdispatch_revision }}
          path: ${{ github.workspace }}/SourceCache/swift-corelibs-libdispatch
          show-progress: false
      - uses: actions/checkout@v4.2.2
        with:
          repository: apple/swift-corelibs-foundation
          ref: ${{ inputs.swift_corelibs_foundation_revision }}
          path: ${{ github.workspace }}/SourceCache/swift-corelibs-foundation
          show-progress: false
      - uses: actions/checkout@v4.2.2
        with:
          repository: apple/swift-foundation
          ref: ${{ inputs.swift_foundation_revision }}
          path: ${{ github.workspace }}/SourceCache/swift-foundation
          show-progress: false
      - uses: actions/checkout@v4.2.2
        with:
          repository: apple/swift-foundation-icu
          ref: ${{ inputs.swift_foundation_icu_revision }}
          path: ${{ github.workspace }}/SourceCache/swift-foundation-icu
          show-progress: false
      - uses: actions/checkout@v4.2.2
        with:
          repository: apple/swift-collections
          ref: ${{ inputs.swift_collections_revision }}
          path: ${{ github.workspace }}/SourceCache/swift-collections
          show-progress: false
      - uses: actions/checkout@v4.2.2
        with:
          repository: swiftlang/swift-corelibs-xctest
          ref: ${{ inputs.swift_corelibs_xctest_revision }}
          path: ${{ github.workspace }}/SourceCache/swift-corelibs-xctest
          show-progress: false
      - uses: actions/checkout@v4.2.2
        with:
          repository: swiftlang/swift-testing
          ref: ${{ inputs.swift_testing_revision }}
          path: ${{ github.workspace }}/SourceCache/swift-testing
          show-progress: false

      - name: Setup environment
        run: |
          $RTLPath = cygpath -w ${{ github.workspace }}/BinaryCache/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk/usr/bin
          echo ${RTLPath} | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

          $SDKRoot = cygpath -w ${{ github.workspace }}/BinaryCache/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk
          echo "SDKROOT=${SDKRoot}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      # FIXME(compnerd): workaround CMake 3.29-3.30 issue
      - uses: lukka/get-cmake@aa1df13cce8c30d2cb58efa871271c5a764623f8 # main
        with:
          cmakeVersion: 3.28.6

      - uses: nttld/setup-ndk@v1
        if: inputs.os == 'Android'
        id: setup-ndk
        with:
          ndk-version: ${{ inputs.ANDROID_NDK_VERSION }}
          local-cache: true

      - name: Create vfs-overlay
        if: inputs.os == 'Windows'
        run: |
          $VfsOverlay = "${{ github.workspace }}/BinaryCache/swift/stdlib/windows-vfs-overlay.yaml"
          $ModuleMapDir =  cygpath -m "${{ github.workspace }}/BinaryCache/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk/usr/share"
          $Win10SdkRoot = Get-ItemPropertyValue `
            -Path "Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Kits\Installed Roots" `
            -Name "KitsRoot10"
          $Win10SdkRoot = cygpath -m "${Win10SdkRoot}"
          $InstallerLocation = Join-Path "${env:ProgramFiles(x86)}" "Microsoft Visual Studio" "Installer"
          $VsWhere = Join-Path "${InstallerLocation}" "vswhere.exe"
          $VsInstallPath = (& "$VsWhere" -latest -products * -format json | ConvertFrom-Json).installationPath
          $VsInstallPath = cygpath -m "${VsInstallPath}"

          $ModuleMap = @"
          version: 0
          use-external-names: false
          case-sensitive: false
          roots:
            - name: "${Win10SdkRoot}/Include/${env:UCRTVersion}/um"
              type: directory
              contents:
                - name: module.modulemap
                  type: file
                  external-contents: "${ModuleMapDir}/winsdk.modulemap"
            - name: "${Win10SdkRoot}/Include/${env:UCRTVersion}/ucrt"
              type: directory
              contents:
                - name: module.modulemap
                  type: file
                  external-contents: "${ModuleMapDir}/ucrt.modulemap"
            - name: "${VsInstallPath}/VC/Tools/MSVC/${env:VCToolsVersion}/include"
              type: directory
              contents:
                - name: module.modulemap
                  type: file
                  external-contents: "${ModuleMapDir}/vcruntime.modulemap"
                - name: vcruntime.apinotes
                  type: file
                  external-contents: "${ModuleMapDir}/vcruntime.apinotes"
          "@

          $VfsOverlayDir = Split-Path -Parent $VfsOverlay
          New-Item -ItemType Directory -Path $VfsOverlayDir
          Write-Output $ModuleMap | Out-File -FilePath $VfsOverlay -Encoding utf8

      - name: Configure libdispatch
        run: |
          # Workaround CMake 3.20 issue
          $CLANG_CL = cygpath -m "${{ github.workspace }}/BinaryCache/Library/Developer/Toolchains/${{ inputs.swift_version }}+Asserts/usr/bin/clang-cl.exe"
          $SWIFTC = cygpath -m "${{ github.workspace }}/BinaryCache/Library/Developer/Toolchains/${{ inputs.swift_version }}+Asserts/usr/bin/swiftc.exe"

          if ("${{ inputs.os }}" -eq "Android") {
            $NDKPATH = cygpath -m "${{ steps.setup-ndk.outputs.ndk-path }}"
            # Since win/arm64 doesn't have one, this logic is necessary because
            # passing an empty CMAKE_ANDROID_NDK value causes a failure.
            $CMAKE_NDK_FLAG = "-DCMAKE_ANDROID_NDK=$NDKPATH"
            $SWIFT_NDK_FLAG = "-DSWIFT_ANDROID_NDK_PATH=$NDKPATH"
          }

          $WINDOWS_VFS_OVERLAY = cygpath -m "${{ github.workspace }}/BinaryCache/swift/stdlib/windows-vfs-overlay.yaml"
          $OVERLAY_FLAGS = if ("${{ inputs.os }}" -eq "Windows") {
            "-vfsoverlay ${WINDOWS_VFS_OVERLAY} -strict-implicit-module-context -Xcc -Xclang -Xcc -fbuiltin-headers-in-system-modules"
          } else {
            ""
          }

          $CMAKE_CPU = if ("${{ inputs.cpu }}" -eq "armv7") { "armv7-a" } else { "${{ inputs.cpu }}" }
          $BUILD_SHARED_LIBS = if ("${{ inputs.sdk_type }}" -eq "dynamic") { "YES" } else { "NO" }
          $InstallSDKRoot = if ("${{ inputs.sdk_type }}" -eq "dynamic") {
            "${{ github.workspace }}/BuildRoot/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}.sdk"
          } else {
            "${{ github.workspace }}/BuildRoot/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}Experimental.sdk"
          }
          $BinarySwiftLibDir = if ("${{ inputs.sdk_type }}" -eq "dynamic") {
            "${{ github.workspace }}/BinaryCache/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}.sdk/usr/lib/swift"
          } else {
            "${{ github.workspace }}/BinaryCache/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}Experimental.sdk/usr/lib/swift_static"
          }
          cmake -B ${{ github.workspace }}/BinaryCache/libdispatch `
                -D BUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} `
                -D CMAKE_BUILD_TYPE=Release `
                -D CMAKE_C_COMPILER=${{ inputs.cc }} `
                -D CMAKE_C_COMPILER_LAUNCHER=sccache `
                -D CMAKE_C_COMPILER_TARGET=${{ inputs.triple }} `
                -D CMAKE_C_FLAGS="${{ inputs.cflags }}" `
                -D CMAKE_CXX_COMPILER=${{ inputs.cxx }} `
                -D CMAKE_CXX_COMPILER_LAUNCHER=sccache `
                -D CMAKE_CXX_COMPILER_TARGET=${{ inputs.triple }} `
                -D CMAKE_CXX_FLAGS="${{ inputs.cxxflags }}" `
                -D CMAKE_INSTALL_PREFIX="${InstallSDKRoot}/usr" `
                -D CMAKE_Swift_COMPILER=${SWIFTC} `
                -D CMAKE_Swift_COMPILER_TARGET=${{ inputs.triple_no_api_level }} `
                -D CMAKE_Swift_FLAGS="-resource-dir ${BinarySwiftLibDir} -L${BinarySwiftLibDir}/${{ inputs.os }} ${OVERLAY_FLAGS} ${{ inputs.swiftflags }}" `
                -D CMAKE_Swift_FLAGS_RELEASE="-O" `
                -D CMAKE_SYSTEM_NAME=${{ inputs.os }} `
                -D CMAKE_SYSTEM_PROCESSOR=${CMAKE_CPU} `
                -D MSVC_C_ARCHITECTURE_ID=${{ inputs.arch }} `
                -D MSVC_CXX_ARCHITECTURE_ID=${{ inputs.arch }} `
                ${{ inputs.linker_flags }} `
                ${{ inputs.extra_flags }} `
                $CMAKE_NDK_FLAG `
                $SWIFT_NDK_FLAG `
                -G Ninja `
                -S ${{ github.workspace }}/SourceCache/swift-corelibs-libdispatch `
                -D BUILD_TESTING=NO `
                -D ENABLE_SWIFT=YES
      - name: Build libdispatch
        run: |
          cmake --build ${{ github.workspace }}/BinaryCache/libdispatch

      - name: Configure Foundation
        run: |
          # Workaround CMake 3.20 issue
          $CLANG_CL = cygpath -m "${{ github.workspace }}/BinaryCache/Library/Developer/Toolchains/${{ inputs.swift_version }}+Asserts/usr/bin/clang-cl.exe"
          $SWIFTC = cygpath -m "${{ github.workspace }}/BinaryCache/Library/Developer/Toolchains/${{ inputs.swift_version }}+Asserts/usr/bin/swiftc.exe"

          if ("${{ inputs.os }}" -eq "Android") {
            $NDKPATH = cygpath -m "${{ steps.setup-ndk.outputs.ndk-path }}"
            # Since win/arm64 doesn't have one, this logic is necessary because
            # passing an empty CMAKE_ANDROID_NDK value causes a failure.
            $CMAKE_NDK_FLAG = "-DCMAKE_ANDROID_NDK=$NDKPATH"
            $SWIFT_NDK_FLAG = "-DSWIFT_ANDROID_NDK_PATH=$NDKPATH"
          }

          $WINDOWS_VFS_OVERLAY = cygpath -m "${{ github.workspace }}/BinaryCache/swift/stdlib/windows-vfs-overlay.yaml"
          $OVERLAY_FLAGS = if ("${{ inputs.os }}" -eq "Windows") {
            "-vfsoverlay ${WINDOWS_VFS_OVERLAY} -strict-implicit-module-context -Xcc -Xclang -Xcc -fbuiltin-headers-in-system-modules"
          } else {
            ""
          }

          $CMAKE_CPU = if ("${{ inputs.cpu }}" -eq "armv7") { "armv7-a" } else { "${{ inputs.cpu }}" }

          $DEFINITION_FLAG = if ("${{ inputs.os }}" -eq "Windows") { "/D" } else { "-D" }
          $LIBZ = if ("${{ inputs.os }}" -eq "Windows") { "zlibstatic.lib" } else { "libz.a" }

          $SWIFT_FOUNDATION_SOURCE_DIR = "${{ github.workspace }}/SourceCache/swift-foundation"
          $SWIFT_FOUNDATION_ICU_SOURCE_DIR = "${{ github.workspace }}/SourceCache/swift-foundation-icu"
          $SWIFT_COLLECTIONS_SOURCE_DIR = "${{ github.workspace }}/SourceCache/swift-collections"

          $build_tools = if ("${{ inputs.os }}" -eq "Windows") { "YES" } else { "NO" }
          $BUILD_SHARED_LIBS = if ("${{ inputs.sdk_type }}" -eq "dynamic") { "YES" } else { "NO" }
          $InstallSDKRoot = if ("${{ inputs.sdk_type }}" -eq "dynamic") {
            "${{ github.workspace }}/BuildRoot/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}Experimental.sdk"
          } else {
            "${{ github.workspace }}/BuildRoot/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}.sdk"
          }
          $BinarySwiftLibDir = if ("${{ inputs.sdk_type }}" -eq "dynamic") {
            "${{ github.workspace }}/BinaryCache/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}Experimental.sdk/usr/lib/swift"
          } else {
            "${{ github.workspace }}/BinaryCache/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}.sdk/usr/lib/swift_static"
          }

          cmake -B ${{ github.workspace }}/BinaryCache/foundation `
                -D BUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} `
                -D CMAKE_ASM_COMPILE_OPTIONS_MSVC_RUNTIME_LIBRARY_MultiThreadedDLL="/MD" `
                -D CMAKE_ASM_FLAGS="--target=${{ inputs.triple }}" `
                -D CMAKE_BUILD_TYPE=Release `
                -D CMAKE_C_COMPILER=${{ inputs.cc }} `
                -D CMAKE_C_COMPILER_TARGET=${{ inputs.triple }} `
                -D CMAKE_C_FLAGS="${{ inputs.cflags }}" `
                -D CMAKE_CXX_COMPILER=${{ inputs.cxx }} `
                -D CMAKE_CXX_COMPILER_TARGET=${{ inputs.triple }} `
                -D CMAKE_CXX_FLAGS="${{ inputs.cxxflags }}" `
                -D CMAKE_FIND_PACKAGE_PREFER_CONFIG=YES `
                -D CMAKE_INSTALL_PREFIX="${InstallSDKRoot}/usr" `
                -D CMAKE_Swift_COMPILER=${SWIFTC} `
                -D CMAKE_Swift_COMPILER_TARGET=${{ inputs.triple_no_api_level }} `
                -D CMAKE_Swift_FLAGS="-resource-dir ${BinarySwiftLibDir} -L${BinarySwiftLibDir}/${{ inputs.os }} ${OVERLAY_FLAGS} ${{ inputs.swiftflags }}" `
                -D CMAKE_Swift_FLAGS_RELEASE="-O" `
                -D CMAKE_SYSTEM_NAME=${{ inputs.os }} `
                -D CMAKE_SYSTEM_PROCESSOR=${CMAKE_CPU} `
                -D MSVC_C_ARCHITECTURE_ID=${{ inputs.arch }} `
                -D MSVC_CXX_ARCHITECTURE_ID=${{ inputs.arch }} `
                ${{ inputs.linker_flags }} `
                ${{ inputs.extra_flags }} `
                $CMAKE_NDK_FLAG `
                $SWIFT_NDK_FLAG `
                -G Ninja `
                -S ${{ github.workspace }}/SourceCache/swift-corelibs-foundation `
                -D dispatch_DIR=${{ github.workspace }}/BinaryCache/libdispatch/cmake/modules `
                -D CURL_DIR=${{ github.workspace }}/BuildRoot/Library/curl-${{ inputs.curl_version }}/usr/lib/cmake/CURL `
                -D FOUNDATION_BUILD_TOOLS=${build_tools} `
                -D Foundation_MACRO=${{ github.workspace }}/BuildRoot/Library/Developer/Toolchains/${{ inputs.swift_version }}+Asserts/usr/bin `
                -D ENABLE_TESTING=NO `
                -D _SwiftFoundation_SourceDIR=$SWIFT_FOUNDATION_SOURCE_DIR `
                -D _SwiftFoundationICU_SourceDIR=$SWIFT_FOUNDATION_ICU_SOURCE_DIR `
                -D _SwiftCollections_SourceDIR=$SWIFT_COLLECTIONS_SOURCE_DIR `
                -D LibXml2_DIR=${{ github.workspace }}/BuildRoot/Library/libxml2-${{ inputs.libxml2_version }}/usr/lib/cmake/libxml2-${{ inputs.libxml2_version }} `
                -D ZLIB_ROOT=${{ github.workspace }}/BuildRoot/Library/zlib-${{ inputs.zlib_version }}/usr `
                -D ZLIB_LIBRARY=${{ github.workspace }}/BuildRoot/Library/zlib-${{ inputs.zlib_version }}/usr/lib/$LIBZ `
                -D SwiftFoundation_MACRO=${{ github.workspace }}/BinaryCache/Library/Developer/Toolchains/${{ inputs.swift_version }}+Asserts/usr/bin
      - name: Build foundation
        run: |
          cmake --build ${{ github.workspace }}/BinaryCache/foundation

      # TODO(compnerd) correctly version XCTest
      - name: Configure xctest
        run: |
          # Workaround CMake 3.20 issue
          $CLANG_CL = cygpath -m "${{ github.workspace }}/BinaryCache/Library/Developer/Toolchains/${{ inputs.swift_version }}+Asserts/usr/bin/clang-cl.exe"
          $SWIFTC = cygpath -m "${{ github.workspace }}/BinaryCache/Library/Developer/Toolchains/${{ inputs.swift_version }}+Asserts/usr/bin/swiftc.exe"

          if ("${{ inputs.os }}" -eq "Android") {
            $NDKPATH = cygpath -m "${{ steps.setup-ndk.outputs.ndk-path }}"
            # Since win/arm64 doesn't have one, this logic is necessary because
            # passing an empty CMAKE_ANDROID_NDK value causes a failure.
            $CMAKE_NDK_FLAG = "-DCMAKE_ANDROID_NDK=$NDKPATH"
            $SWIFT_NDK_FLAG = "-DSWIFT_ANDROID_NDK_PATH=$NDKPATH"
          }

          $WINDOWS_VFS_OVERLAY = cygpath -m "${{ github.workspace }}/BinaryCache/swift/stdlib/windows-vfs-overlay.yaml"
          $OVERLAY_FLAGS = if ("${{ inputs.os }}" -eq "Windows") {
            "-vfsoverlay ${WINDOWS_VFS_OVERLAY} -strict-implicit-module-context -Xcc -Xclang -Xcc -fbuiltin-headers-in-system-modules"
          } else {
            ""
          }

          $CMAKE_CPU = if ("${{ inputs.cpu }}" -eq "armv7") { "armv7-a" } else { "${{ inputs.cpu }}" }

          $XCTestBinDir = switch ("${{ inputs.cpu }}") {
          "armv7" { "bin32a" }
          "i686" { "bin32" }
          "x86_64" { "bin64" }
          "aarch64" { "bin64a" }
          }
          $BUILD_SHARED_LIBS = if ("${{ inputs.sdk_type }}" -eq "dynamic") { "YES" } else { "NO" }
          $InstallSDKRoot = if ("${{ inputs.sdk_type }}" -eq "dynamic") {
            "${{ github.workspace }}/BuildRoot/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}Experimental.sdk"
          } else {
            "${{ github.workspace }}/BuildRoot/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}.sdk"
          }
          $BinarySwiftLibDir = if ("${{ inputs.sdk_type }}" -eq "dynamic") {
            "${{ github.workspace }}/BinaryCache/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}Experimental.sdk/usr/lib/swift"
          } else {
            "${{ github.workspace }}/BinaryCache/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}.sdk/usr/lib/swift_static"
          }

          cmake -B ${{ github.workspace }}/BinaryCache/xctest `
                -D BUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} `
                -D CMAKE_BUILD_TYPE=Release `
                -D CMAKE_BUILD_WITH_INSTALL_RPATH=YES `
                -D CMAKE_C_COMPILER=${{ inputs.cc }} `
                -D CMAKE_C_COMPILER_LAUNCHER=sccache `
                -D CMAKE_C_COMPILER_TARGET=${{ inputs.triple }} `
                -D CMAKE_C_FLAGS="${{ inputs.cflags }}" `
                -D CMAKE_CXX_COMPILER=${{ inputs.cxx }} `
                -D CMAKE_CXX_COMPILER_LAUNCHER=sccache `
                -D CMAKE_CXX_COMPILER_TARGET=${{ inputs.triple }} `
                -D CMAKE_CXX_FLAGS="${{ inputs.cxxflags }}" `
                -D CMAKE_INSTALL_BINDIR=$XCTestBinDir `
                -D CMAKE_INSTALL_PREFIX="${InstallSDKRoot}/usr" `
                -D CMAKE_Swift_COMPILER=${SWIFTC} `
                -D CMAKE_Swift_COMPILER_TARGET=${{ inputs.triple_no_api_level }} `
                -D CMAKE_Swift_FLAGS="-resource-dir ${BinarySwiftLibDir} -L${BinarySwiftLibDir}/${{ inputs.os }} ${OVERLAY_FLAGS} ${{ inputs.swiftflags }}" `
                -D CMAKE_Swift_FLAGS_RELEASE="-O" `
                -D CMAKE_SYSTEM_NAME=${{ inputs.os }} `
                -D CMAKE_SYSTEM_PROCESSOR=${CMAKE_CPU} `
                ${{ inputs.linker_flags }} `
                ${{ inputs.extra_flags }} `
                $CMAKE_NDK_FLAG `
                $SWIFT_NDK_FLAG `
                -G Ninja `
                -S ${{ github.workspace }}/SourceCache/swift-corelibs-xctest `
                -D dispatch_DIR=${{ github.workspace }}/BinaryCache/libdispatch/cmake/modules `
                -D Foundation_DIR=${{ github.workspace }}/BinaryCache/foundation/cmake/modules `
                -D ENABLE_TESTING=NO `
                -D XCTest_INSTALL_NESTED_SUBDIR=YES
      - name: Build xctest
        run: |
          cmake --build ${{ github.workspace }}/BinaryCache/xctest

      - name: Configure Testing
        run: |
          # Workaround CMake 3.20 issue
          $CLANG_CL = cygpath -m "${{ github.workspace }}/BinaryCache/Library/Developer/Toolchains/${{ inputs.swift_version }}+Asserts/usr/bin/clang-cl.exe"
          $SWIFTC = cygpath -m "${{ github.workspace }}/BinaryCache/Library/Developer/Toolchains/${{ inputs.swift_version }}+Asserts/usr/bin/swiftc.exe"

          if ("${{ inputs.os }}" -eq "Android") {
            $NDKPATH = cygpath -m "${{ steps.setup-ndk.outputs.ndk-path }}"
            # Since win/arm64 doesn't have one, this logic is necessary because
            # passing an empty CMAKE_ANDROID_NDK value causes a failure.
            $CMAKE_NDK_FLAG = "-DCMAKE_ANDROID_NDK=$NDKPATH"
            $SWIFT_NDK_FLAG = "-DSWIFT_ANDROID_NDK_PATH=$NDKPATH"
          }

          $WINDOWS_VFS_OVERLAY = cygpath -m "${{ github.workspace }}/BinaryCache/swift/stdlib/windows-vfs-overlay.yaml"
          $OVERLAY_FLAGS = if ("${{ inputs.os }}" -eq "Windows") {
            "-vfsoverlay ${WINDOWS_VFS_OVERLAY} -strict-implicit-module-context -Xcc -Xclang -Xcc -fbuiltin-headers-in-system-modules"
          } else {
            ""
          }

          # Workaround the issue of not using the new Swift driver , that forces us to disable the CMP0157 policy.
          (Get-Content -Path "${{ github.workspace }}\SourceCache\swift-testing\CMakeLists.txt") -replace 'cmake_policy\(SET CMP0157 NEW\)', 'cmake_policy(SET CMP0157 OLD)' | Set-Content -Path "${{ github.workspace }}\SourceCache\swift-testing\CMakeLists.txt"

          $CMAKE_CPU = if ("${{ inputs.cpu }}" -eq "armv7") { "armv7-a" } else { "${{ inputs.cpu }}" }

          $TestingBinDir = switch ("${{ inputs.cpu }}") {
          "armv7" { "bin32a" }
          "i686" { "bin32" }
          "x86_64" { "bin64" }
          "aarch64" { "bin64a" }
          }

          $BUILD_SHARED_LIBS = if ("${{ inputs.sdk_type }}" -eq "dynamic") { "YES" } else { "NO" }
          $InstallSDKRoot = if ("${{ inputs.sdk_type }}" -eq "dynamic") {
            "${{ github.workspace }}/BuildRoot/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}Experimental.sdk"
          } else {
            "${{ github.workspace }}/BuildRoot/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}.sdk"
          }
          $BinarySwiftLibDir = if ("${{ inputs.sdk_type }}" -eq "dynamic") {
            "${{ github.workspace }}/BinaryCache/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}Experimental.sdk/usr/lib/swift"
          } else {
            "${{ github.workspace }}/BinaryCache/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}.sdk/usr/lib/swift_static"
          }

          cmake -B ${{ github.workspace }}/BinaryCache/testing `
                -D BUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} `
                -D CMAKE_BUILD_TYPE=Release `
                -D CMAKE_BUILD_WITH_INSTALL_RPATH=YES `
                -D CMAKE_CXX_COMPILER=${{ inputs.cxx }} `
                -D CMAKE_CXX_COMPILER_LAUNCHER=sccache `
                -D CMAKE_CXX_COMPILER_TARGET=${{ inputs.triple }} `
                -D CMAKE_CXX_FLAGS="${{ inputs.cxxflags }}" `
                -D CMAKE_INSTALL_BINDIR=$TestingBinDir `
                -D CMAKE_INSTALL_PREFIX="${InstallSDKRoot}/usr" `
                -D CMAKE_Swift_COMPILER=${SWIFTC} `
                -D CMAKE_Swift_COMPILER_TARGET=${{ inputs.triple_no_api_level }} `
                -D CMAKE_Swift_FLAGS="-package-name swift_testing -resource-dir ${BinarySwiftLibDir} -L${BinarySwiftLibDir}/${{ inputs.os }} ${OVERLAY_FLAGS} ${{ inputs.swiftflags }}" `
                -D CMAKE_Swift_FLAGS_RELEASE="-O" `
                -D CMAKE_SYSTEM_NAME=${{ inputs.os }} `
                -D CMAKE_SYSTEM_PROCESSOR=${CMAKE_CPU} `
                ${{ inputs.linker_flags }} `
                ${{ inputs.extra_flags }} `
                $CMAKE_NDK_FLAG `
                $SWIFT_NDK_FLAG `
                -G Ninja `
                -S ${{ github.workspace }}/SourceCache/swift-testing `
                -D dispatch_DIR=${{ github.workspace }}/BinaryCache/libdispatch/cmake/modules `
                -D Foundation_DIR=${{ github.workspace }}/BinaryCache/foundation/cmake/modules `
                -D SwiftTesting_INSTALL_NESTED_SUBDIR=YES `
                -D SwiftTesting_MACRO=${{ github.workspace }}/BinaryCache/Library/Developer/Toolchains/${{ inputs.swift_version }}+Asserts/usr/bin/TestingMacros.dll
      - name: Build Testing
        run: |
          cmake --build ${{ github.workspace }}/BinaryCache/testing

      - name: Install Testing
        run: |
          cmake --build ${{ github.workspace }}/BinaryCache/testing --target install
      - name: Install xctest
        run: |
          cmake --build ${{ github.workspace }}/BinaryCache/xctest --target install
      - name: Install foundation
        run: |
          cmake --build ${{ github.workspace }}/BinaryCache/foundation --target install
      - name: Install libdispatch
        run: |
          cmake --build ${{ github.workspace }}/BinaryCache/libdispatch --target install

      - uses: actions/setup-python@v5
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import plistlib

            info_plist = r'${{ github.workspace }}/BuildRoot/Library/Developer/Platforms/${{ inputs.os }}.platform/Info.plist'
            with open(os.path.normpath(info_plist), 'wb') as plist:
              # TODO(compnerd) derive this from the install directory
              plistlib.dump({ 'DefaultProperties': { 'XCTEST_VERSION': '${{ inputs.swift_version }}', 'TESTING_VERSION': '${{ inputs.swift_version }}', 'SWIFTC_FLAGS': ['-use-ld=lld'] } }, plist)

            sdk_settings_plist = r'${{ github.workspace }}/BuildRoot/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}.sdk/SDKSettings.plist'
            with open(os.path.normpath(sdk_settings_plist), 'wb') as plist:
              # TODO(compnerd) derive this from the CMAKE_BUILD_TYPE for the
              # runtime.
              plistlib.dump({ 'DefaultProperties': { 'DEFAULT_USE_RUNTIME': 'MD' } }, plist)

      - name: Create SDKSettings.json
        run: |
          $SDKSettings = @{
            CanonicalName = "${{ inputs.triple }}"
            DisplayName = "${{ inputs.os }}"
            IsBaseSDK = "NO"
            Version = "${{ inputs.swift_version }}"
            VersionMap = @{}
            DefaultProperties = @{
              PLATFORM_NAME = "${{ inputs.os }}"
              DEFAULT_COMPILER = [string]::Format(".org.compnerd.dt.toolchain.{0}.{1}-asserts", (Get-Date -Format "yyyymmdd"), ((Get-Date).Hour % 6))
            }
          }
          if ("${{ inputs.os }}" -eq "Windows") {
            $SDKSettings.DefaultProperties.DEFAULT_USE_RUNTIME = "MD"
          }
          New-Item -ItemType Directory -Path "${{ github.workspace }}/BuildRoot/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}.sdk" -Force | Out-Null
          $SDKSettings | ConvertTo-JSON | Out-File -FilePath "${{ github.workspace }}/BuildRoot/Library/Developer/Platforms/${{ inputs.os }}.platform/Developer/SDKs/${{ inputs.os }}.sdk/SDKSettings.json"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.os }}-${{ inputs.arch }}-${{ inputs.sdk_type }}-sdk
          path: ${{ github.workspace }}/BuildRoot/Library/Developer/Platforms/${{ inputs.os }}.platform

      - name: Upload PDBs to Azure
        uses: microsoft/action-publish-symbols@v2.1.6
        if: ${{ inputs.debug_info && inputs.os == 'Windows' }}
        with:
          accountName: ${{ vars.SYMBOL_SERVER_ACCOUNT }}
          personalAccessToken: ${{ secrets.SYMBOL_SERVER_PAT }}
          symbolsFolder: ${{ github.workspace }}/BinaryCache
          searchPattern: '**/*.pdb'

      - name: Upload DLLs to Azure
        uses: microsoft/action-publish-symbols@v2.1.6
        if: ${{ inputs.debug_info && inputs.os == 'Windows' }}
        with:
          accountName: ${{ vars.SYMBOL_SERVER_ACCOUNT }}
          personalAccessToken: ${{ secrets.SYMBOL_SERVER_PAT }}
          symbolsFolder: ${{ github.workspace }}/BinaryCache
          searchPattern: '**/*.dll'
