name: Development Snapshot

on:
  workflow_dispatch:
    inputs:
      swift_version:
        description: 'Swift Version'
        default: '0.0.0'
        required: false
        type: string

      android_api_level:
        description: 'Android API Level'
        default: 28
        required: false
        type: number

      swift_tag:
        description: 'Swift Build Tag'
        required: false
        type: string

      debug_info:
        description: 'Emit PDBs (Debug Info)'
        default: true
        type: boolean

      signed:
        description: 'Code Sign'
        default: false
        type: boolean

      create_release:
        description: 'Create Release'
        type: boolean
        default: true
        required: false

      default_runner:
        description: 'Build runner'
        default: 'windows-latest'
        required: false
        type: string

      compilers_runner:
        description: 'Build runner for `compilers` job'
        type: string
        required: false

  workflow_call:
    inputs:
      swift_version:
        description: 'Swift Version'
        default: '0.0.0'
        required: false
        type: string

      android_api_level:
        description: 'Android API Level'
        default: 28
        required: false
        type: number

      swift_tag:
        description: 'Swift Build Tag'
        required: false
        type: string

      debug_info:
        description: 'Emit PDBs (Debug Info)'
        default: true
        type: boolean

      signed:
        description: 'Code Sign'
        default: false
        type: boolean

      create_release:
        description: 'Create Release'
        type: boolean
        default: true
        required: false

      default_runner:
        description: 'Build runner'
        default: 'windows-latest'
        required: false
        type: string

      compilers_runner:
        description: 'Build runner for `compilers` job'
        type: string
        required: false

    secrets:
      SYMBOL_SERVER_PAT:
        required: true
      CERTIFICATE:
        required: true
      PASSPHRASE:
        required: true

env:
  SCCACHE_DIRECT: yes

jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      curl_revision: ${{ steps.context.outputs.curl_revision }}
      icu_revision: ${{ steps.context.outputs.icu_revision }}
      indexstore_db_revision: ${{ steps.context.outputs.indexstore_db_revision }}
      libxml2_revision: ${{ steps.context.outputs.libxml2_revision }}
      llvm_project_revision: ${{ steps.context.outputs.llvm_project_revision }}
      sourcekit_lsp_revision: ${{ steps.context.outputs.sourcekit_lsp_revision }}
      swift_argument_parser_revision: ${{ steps.context.outputs.swift_argument_parser_revision }}
      swift_asn1_revision: ${{ steps.context.outputs.swift_asn1_revision }}
      swift_atomics_revision: ${{ steps.context.outputs.swift_atomics_revision }}
      swift_certificates_revision: ${{ steps.context.outputs.swift_certificates_revision }}
      swift_cmark_revision: ${{ steps.context.outputs.swift_cmark_revision }}
      swift_collections_revision: ${{ steps.context.outputs.swift_collections_revision }}
      swift_corelibs_foundation_revision: ${{ steps.context.outputs.swift_corelibs_foundation_revision }}
      swift_corelibs_libdispatch_revision: ${{ steps.context.outputs.swift_corelibs_libdispatch_revision }}
      swift_corelibs_xctest_revision: ${{ steps.context.outputs.swift_corelibs_xctest_revision }}
      swift_crypto_revision: ${{ steps.context.outputs.swift_crypto_revision }}
      swift_driver_revision: ${{ steps.context.outputs.swift_driver_revision }}
      swift_experimental_string_processing_revision: ${{ steps.context.outputs.swift_experimental_string_processing_revision }}
      swift_format_revision: ${{ steps.context.outputs.swift_format_revision }}
      swift_foundation_revision: ${{ steps.context.outputs.swift_foundation_revision }}
      swift_foundation_icu_revision: ${{ steps.context.outputs.swift_foundation_icu_revision }}
      swift_installer_scripts_revision: ${{ steps.context.outputs.swift_installer_scripts_revision }}
      swift_llbuild_revision: ${{ steps.context.outputs.swift_llbuild_revision }}
      swift_markdown_revision: ${{ steps.context.outputs.swift_markdown_revision }}
      swift_package_manager_revision: ${{ steps.context.outputs.swift_package_manager_revision }}
      swift_revision: ${{ steps.context.outputs.swift_revision }}
      swift_syntax_revision: ${{ steps.context.outputs.swift_syntax_revision }}
      swift_system_revision: ${{ steps.context.outputs.swift_system_revision }}
      swift_tools_support_core_revision: ${{ steps.context.outputs.swift_tools_support_core_revision }}
      yams_revision: ${{ steps.context.outputs.yams_revision }}
      zlib_revision: ${{ steps.context.outputs.zlib_revision }}
      ANDROID_API_LEVEL: ${{ steps.context.outputs.ANDROID_API_LEVEL }}
      WINDOWS_CMAKE_C_FLAGS: ${{ steps.context.outputs.WINDOWS_CMAKE_C_FLAGS }}
      WINDOWS_CMAKE_CXX_FLAGS: ${{ steps.context.outputs.WINDOWS_CMAKE_CXX_FLAGS }}
      WINDOWS_CMAKE_EXE_LINKER_FLAGS: ${{ steps.context.outputs.WINDOWS_CMAKE_EXE_LINKER_FLAGS }}
      WINDOWS_CMAKE_SHARED_LINKER_FLAGS: ${{ steps.context.outputs.WINDOWS_CMAKE_SHARED_LINKER_FLAGS }}
      ANDROID_CMAKE_C_FLAGS: ${{ steps.context.outputs.ANDROID_CMAKE_C_FLAGS }}
      ANDROID_CMAKE_CXX_FLAGS: ${{ steps.context.outputs.ANDROID_CMAKE_CXX_FLAGS }}
      ANDROID_CMAKE_EXE_LINKER_FLAGS: ${{ steps.context.outputs.ANDROID_CMAKE_EXE_LINKER_FLAGS }}
      ANDROID_CMAKE_SHARED_LINKER_FLAGS: ${{ steps.context.outputs.ANDROID_CMAKE_SHARED_LINKER_FLAGS }}
      CMAKE_Swift_FLAGS: ${{ steps.context.outputs.CMAKE_Swift_FLAGS }}
      debug_info: ${{ steps.context.outputs.debug_info }}
      signed: ${{ steps.context.outputs.signed }}
      swift_version: ${{ steps.context.outputs.swift_version }}
      swift_tag: ${{ steps.context.outputs.swift_tag }}
      windows_build_runner: ${{ steps.context.outputs.windows_build_runner }}
      compilers_build_runner: ${{ steps.context.outputs.compilers_build_runner }}
    steps:
      - id: context
        name: Generate Build Context
        run: |
          # TODO(compnerd) can we make this more silent?
          sudo DEBIAN_FRONTEND=noninteractive apt-get -qq update -yq
          sudo DEBIAN_FRONTEND=noninteractive apt-get -qq -o Dpkg::Use-Pty=0 install -yq repo libxml2-utils

          # Which branch is this workflow based on
          branch_version_string=${{ inputs.swift_version || '0.0.0' }}
          if [[ $branch_version_string == *.* ]]; then
            branch_name=$(echo ${branch_version_string} | awk -F. '{ ver=$1"."$2; print (ver == "0.0") ? "main" : "release/"ver }')
          else
            branch_name="release/$branch_version_string"
          fi

          repo init --quiet --groups default --depth 1 -u https://github.com/thebrowsercompany/swift-build -b hyp/attempt-inspect-runtime-install3
          repo sync --quiet --no-clone-bundle --no-tags --jobs $(nproc --all)

          if [[ "${{ inputs.swift_tag }}" != "" ]] ; then
            tee -a "${GITHUB_OUTPUT}" <<-EOF
          indexstore_db_revision=refs/tags/${{ inputs.swift_tag }}
          llvm_project_revision=refs/tags/${{ inputs.swift_tag }}
          sourcekit_lsp_revision=refs/tags/${{ inputs.swift_tag }}
          swift_revision=refs/tags/${{ inputs.swift_tag }}
          swift_argument_parser_revision=refs/tags/1.4.0
          swift_asn1_revision=refs/tags/0.7.0
          swift_atomics_revision=refs/tags/1.2.0
          swift_certificates_revision=refs/tags/0.1.0
          swift_cmark_revision=refs/tags/${{ inputs.swift_tag }}
          swift_collections_revision=refs/tags/1.1.2
          swift_corelibs_foundation_revision=refs/tags/${{ inputs.swift_tag }}
          swift_corelibs_libdispatch_revision=refs/tags/${{ inputs.swift_tag }}
          swift_corelibs_xctest_revision=refs/tags/${{ inputs.swift_tag }}
          swift_crypto_revision=refs/tags/3.0.0
          swift_driver_revision=refs/tags/${{ inputs.swift_tag }}
          swift_experimental_string_processing_revision=refs/tags/${{ inputs.swift_tag }}
          swift_format_revision=refs/heads/main
          swift_foundation_revison=refs/heads/main
          swift_foundation_icu_revision=refs/tags/0.0.8
          swift_installer_scripts_revision=refs/heads/main
          swift_llbuild_revision=refs/tags/${{ inputs.swift_tag }}
          swift_markdown_revision=refs/tags/${{ inputs.swift_tag }}
          swift_package_manager_revision=refs/tags/${{ inputs.swift_tag }}
          swift_syntax_revision=refs/tags/${{ inputs.swift_tag }}
          swift_system_revision=refs/tags/1.3.0
          swift_tools_support_core_revision=refs/tags/${{ inputs.swift_tag }}
          curl_revision=refs/tags/curl-8_5_0
          libxml2_revision=refs/tags/v2.11.5
          yams_revision=refs/tags/5.0.6
          zlib_revision=refs/tags/v1.3.1
          icu_revision=refs/heads/maint/maint-69
          EOF
          else
            repo manifest -r --suppress-upstream-revision --suppress-dest-branch | \
                  xmllint --xpath "//project/@name | //project/@revision" - | \
                  xargs -n2 | \
                  awk -F'[= ]' '{
                    split($2, repo, "/");
                    gsub(/-/, "_", repo[2]);
                    print tolower(repo[2]) "_revision=" $4
                  }' | tee -a "${GITHUB_OUTPUT}"
            repo manifest -r --suppress-upstream-revision --suppress-dest-branch -o - | sed -E 's,[[:space:]]+$,,' > stable.xml
          fi

          # FIXME(z2oh): Remove /D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR when GitHub runner image updates to 20240610.1.
          #  see: https://github.com/actions/runner-images/issues/10004
          if [[ "${{ github.event_name }}" == "schedule" || "${{ inputs.debug_info }}" == "true" ]]; then
            echo debug_info=true >> ${GITHUB_OUTPUT}
            echo WINDOWS_CMAKE_C_FLAGS="/GS- /Gw /Gy /Oi /Oy /Z7 /Zc:inline /Zc:preprocessor" >> ${GITHUB_OUTPUT}
            echo WINDOWS_CMAKE_CXX_FLAGS="/GS- /Gw /Gy /Oi /Oy /Z7 /Zc:inline /Zc:preprocessor /Zc:__cplusplus /D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR" >> ${GITHUB_OUTPUT}
            echo ANDROID_CMAKE_C_FLAGS="-ffunction-sections -fdata-sections -g" >> ${GITHUB_OUTPUT}
            echo ANDROID_CMAKE_CXX_FLAGS="-ffunction-sections -fdata-sections -g" >> ${GITHUB_OUTPUT}
            echo WINDOWS_CMAKE_EXE_LINKER_FLAGS="-incremental:no -debug -opt:ref -opt:icf" >> ${GITHUB_OUTPUT}
            echo WINDOWS_CMAKE_SHARED_LINKER_FLAGS="-incremental:no -debug -opt:ref -opt:icf" >> ${GITHUB_OUTPUT}
            echo CMAKE_Swift_FLAGS="-g -debug-info-format=codeview -Xlinker -debug -Xlinker -incremental:no -Xlinker -opt:ref -Xlinker -opt:icf" >> ${GITHUB_OUTPUT}
          else
            echo debug_info=false >> ${GITHUB_OUTPUT}
            echo WINDOWS_CMAKE_C_FLAGS="/GS- /Gw /Gy /Oi /Oy /Zc:inline /Zc:preprocessor" >> ${GITHUB_OUTPUT}
            echo WINDOWS_CMAKE_CXX_FLAGS="/GS- /Gw /Gy /Oi /Oy /Zc:inline /Zc:preprocessor /Zc:__cplusplus /D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR" >> ${GITHUB_OUTPUT}
            echo ANDROID_CMAKE_C_FLAGS="-ffunction-sections -fdata-sections" >> ${GITHUB_OUTPUT}
            echo ANDROID_CMAKE_CXX_FLAGS="-ffunction-sections -fdata-sections" >> ${GITHUB_OUTPUT}
            echo WINDOWS_CMAKE_EXE_LINKER_FLAGS="" >> ${GITHUB_OUTPUT}
            echo WINDOWS_CMAKE_SHARED_LINKER_FLAGS="" >> ${GITHUB_OUTPUT}
            echo CMAKE_Swift_FLAGS="-Xlinker -incremental:no -Xlinker -opt:ref -Xlinker -opt:icf" >> ${GITHUB_OUTPUT}
          fi
          echo ANDROID_CMAKE_EXE_LINKER_FLAGS="" >> ${GITHUB_OUTPUT}
          echo ANDROID_CMAKE_SHARED_LINKER_FLAGS="" >> ${GITHUB_OUTPUT}

          if [[ "${{ github.event_name }}" == "schedule" || "${{ inputs.signed }}" == "true" ]]; then
            # FIXME(compnerd) enable this when requested
            echo signed=false >> ${GITHUB_OUTPUT}
          else
            echo signed=false >> ${GITHUB_OUTPUT}
          fi

          echo swift_version=${{ inputs.swift_version || '0.0.0' }} | tee -a ${GITHUB_OUTPUT}
          if [[ -n "${{ inputs.swift_tag }}" ]] ; then
            echo swift_tag=${{ inputs.swift_tag }} | tee -a ${GITHUB_OUTPUT}
          else
            if [[ "$branch_name" == "main" ]] ; then
              echo swift_tag=$(date +%Y%m%d.$(date +%-H/6 | bc)) | tee -a ${GITHUB_OUTPUT}
            else
              echo swift_tag=swift-"$branch_version_string"-$(date +%Y%m%d.$(date +%-H/6 | bc)) | tee -a ${GITHUB_OUTPUT}
            fi
          fi

          echo windows_build_runner=${{ inputs.default_runner }} >> ${GITHUB_OUTPUT}
          echo compilers_build_runner=${{ inputs.compilers_runner || inputs.default_runner }} >> ${GITHUB_OUTPUT}

          echo ANDROID_API_LEVEL=${{ inputs.android_api_level }} >> ${GITHUB_OUTPUT}

      - uses: actions/upload-artifact@v4
        with:
          name: stable.xml
          path: stable.xml
          if-no-files-found: ignore

  smoke_test:
    needs: [context]
    runs-on: ${{ needs.context.outputs.windows_build_runner }}

    steps:
      - name: Download artifact from previous run
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: your_workflow_file.yml
          run_id: 10182657234
          name: installer-amd64
          path: ${{ github.workspace }}/tmp
          repo: thebrowsercompany/swift-build
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # TODO(compnerd): migrate this to compnerd/gha-setup-swift after the work that @mangini is doing is completed
      - run: |
          function Update-EnvironmentVariables {
            foreach ($level in "Machine", "User") {
              [Environment]::GetEnvironmentVariables($level).GetEnumerator() | % {
                # For Path variables, append the new values, if they're not already in there
                if ($_.Name -Match 'Path$') {
                  $_.Value = ($((Get-Content "Env:$($_.Name)") + ";$($_.Value)") -Split ';' | Select -Unique) -Join ';'
                }
                $_
              } | Set-Content -Path { "Env:$($_.Name)" }
            }
          }

          try {
            Write-Host "Starting Install installer.exe..."
            $Process = Start-Process -FilePath ${{ github.workspace }}/tmp/installer.exe -ArgumentList ("-q") -Wait -PassThru
            $ExitCode = $Process.ExitCode
            if ($ExitCode -eq 0 -or $ExitCode -eq 3010) {
              Write-Host "Installation successful"
            } else {
              Write-Host "non-zero exit code returned by the installation process: $ExitCode"
              exit $ExitCode
            }
          } catch {
            Write-Host "Failed to install: $($_.Exception.Message)"
            exit 1
          }
          Update-EnvironmentVariables

          # Reset Path and environment
          echo "$env:Path" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
          Get-ChildItem Env: | % { echo "$($_.Name)=$($_.Value)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append }

      - run: |
          echo $env:SDKROOT
          Get-ChildItem -Path $env:SDKROOT -Recurse | Select-Object FullName | Format-Table -Wrap
          dir "$env:SDKROOT\..\..\.."
          dir "$env:SDKROOT\..\..\..\Developer"

      - name: Update SDKROOT and run swift build
        run: |
          # Remove trailing backslash from SDKROOT
          $SDKROOT = $env:SDKROOT.TrimEnd('\')
          echo "Updated SDKROOT: $SDKROOT"
          
          # Set the updated SDKROOT for this step and future steps
          echo "SDKROOT=$SDKROOT" >> $env:GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          repository: compnerd/swift-win32
          ref: refs/heads/main
          path: ${{ github.workspace }}/SourceCache/swift-win32
          show-progress: false

      - run: swift build -v
        working-directory: ${{ github.workspace }}/SourceCache/swift-win32

      - run: swift test -Xswiftc -DENABLE_TESTING
        working-directory: ${{ github.workspace }}/SourceCache/swift-win32
